// <auto-generated />
namespace MZDNETWORK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Intialcreate22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intialcreate22));
        
        string IMigrationMetadata.Id
        {
            get { return "202504280526204_Intialcreate22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
